### ISSUE TITLE
Can't match multiple words separated by whitespace

### ISSUE THREAD

**Issue by mkadirtan** [alexzel/bad-words-next#10]
**Describe the bug**
The input word `blow job` doesn't get censored.
```console.log(badwords.check('blow job'))```
Expected: true, Received: true. It can detect there is a badword.
```console.log(badwords.filter('blow job'))```
Expected: *** ***, Received: blow job. It can't filter if the words are separated by whitespace.

**Environment (please complete the following information):**
 - Operating System: [e.g. macOS]
 - Node.js Version: [e.g. v16.17.0]

**Additional context**
I think the main reason is due to this split here: https://github.com/alexzel/bad-words-next/blob/dac98b79a97a6b0e02083a195f4588f728188212/src/index.ts#L326

**Comment by alexzel** [comment]
That is the purpose of the library (and other similar libraries) to check and filter words, and it is mentioned in the readme
https://github.com/alexzel/bad-words-next#notes

> Dictionary words with spaces won't work b/c they do not represent a single word

so in your example the sentence consists of two words `blow` and `job` and neither of them is a bad word.

**Comment by mkadirtan** [comment]
```typescript
    const badwords = new BadWordsNext({
        data: enData,
        spaceChars: [' ']
    });
    let txt = 'blow job';
    console.log(badwords.check(txt)); // true
    console.log(badwords.filter(txt)); // blow job
```
So, is it illegal to add `' '` to spaceChars? I understand blow and job are not badwords, but when they are next to each other that is considered profanity.
```typescript
const badwords = new BadWordsNext({
        data: enData,
    });
    let txt = 'blow-job';
    console.log(badwords.check(txt)); // true
    console.log(badwords.filter(txt)); // ***
```
The above should work with regular spaces, too. But, if that is a limitation of the library I can understand that. If that is an opinion, please consider the above scenario.

**Comment by alexzel** [comment]
Yes, that is the limitation of the library and similar libraries that this one is compared with. The behavior you describe overcomplicates things and means overwriting the entire library, so it will be technically a different package employing different approaches and having a different goal.
