### ISSUE TITLE
BadWordsNext error when using mode: "no-cors"

### ISSUE THREAD

**Issue by supercourseeltpublishing** [alexzel/bad-words-next#22]
**Describe the bug**
I get a TypeError: Cannot read properties of undefined (reading 'replace') at BadWordsNext.prepare, when I do a request with mode: "no-cors". Without the mode: "no-cors" everything works fine.

**Comment by alexzel** [comment]
Sorry, but this library has nothing to do with cross-origin requests and does not implement any kind of server or client.
