### ISSUE TITLE
bug Nothing to repeat” Error in bad-words-next.js at regexp Method

### ISSUE THREAD

**Issue by far310** [alexzel/bad-words-next#23]
Here’s a bug report in English based on the provided issue:

Title: Bug: “Nothing to repeat” Error in bad-words-next.js at regexp Method

Description:
I’m encountering an issue with the bad-words-next library. Specifically, when calling the regexp method at line 1627 in bad-words-next.js, the following error is thrown:

)(?:\d|[!@#$%^&*()[\];:'",.?\-_=+~`|]|a|(?:the)|(?:el)|(?:la))*(?:$|\b|\s)/i: Nothing to repeat

This error appears to occur when trying to create a regular expression, resulting in the failure of the regexp method.

Steps to Reproduce:
	1.	Import and configure bad-words-next in your project.
	2.	Call the regexp method (or any method that triggers it, such as adding words to the filter).
	3.	Observe the error message.

Expected Behavior:
The regular expression should be created correctly without any errors. The library should allow adding words to the filter without any issues.

Actual Behavior:
The error message Nothing to repeat is thrown when trying to create the regular expression. This error disrupts the functionality of the library.

Additional Information:
	•	This issue appears to occur when the regular expression is being dynamically generated, likely due to an incorrect pattern.
	•	The error happens within the file bad-words-next.js at line 1627.
	•	The issue could be related to specific configurations or customizations to the library.

Suggested Fix:
It seems like the error might be caused by an invalid regular expression syntax or an empty value being passed. I would suggest reviewing the regular expression generation logic and ensuring that all patterns are correctly formatted.

Environment:
	•	Library version: bad-words-next
	•	Node.js version: [Provide your Node.js version]
	•	Operating System: [Provide your OS details]

Stack Trace:

at new RegExp (<anonymous>)
at BadWordsNext2.regexp (bad-words-next.js:1627:1)
at BadWordsNext2.add (bad-words-next.js:1598:1)
at textUtils.ts:22:1

This bug report should provide the necessary information to help investigate and resolve the issue you’re encountering.

[ch.json](https://github.com/user-attachments/files/18098313/ch.json)

import BadWordsNext from 'bad-words-next'
import * as ch from './words/ch.json'
import * as de from './words/de.json'
import * as en from './words/en.json'
import * as es from './words/es.json'
import * as fr from './words/fr.json'
import * as pl from './words/pl.json'
import * as ru from './words/ru.json'
import * as ru_lat from './words/ru_lat.json'
import * as ua from './words/ua.json'

// 创建 BadWordsNext 实例
const badwords = new BadWordsNext({ exclusions: ['1u', '1uApp', '1uu.io'] })
badwords.add(en)
badwords.add(es)
badwords.add(fr)
badwords.add(de)
badwords.add(ru)
badwords.add(ru_lat)
badwords.add(ua)
badwords.add(pl)
badwords.add(ch)

// 检查文本中是否包含敏感词
export function checkForProfanity(text: string): boolean {
  return badwords.check(text)
}

// 将文本中的敏感词替换为 ***
export function censorText(text: string): string {
  return badwords.filter(text)
}

// 使用排除项，避免过滤某些敏感词
export function filterWithExclusions(text: string, exclusions: string[]): string {
  const filter = new BadWordsNext({
    data: en,
    exclusions,
  })
  return filter.filter(text)
}

**Comment by alexzel** [comment]
Hi @far310, I can see the problem in your `ch.json` format. Please follow [Dictionary files format](https://github.com/alexzel/bad-words-next?tab=readme-ov-file#dictionary-files-format). You use `+` at the beginning of strings, it should have a previous character which it will treat as repeating character that's why it throws `Nothing to repeat` b/c there is literally nothing to repeat. Also, a lot of strings have leading and trailing spaces which I think should be trimmed. Anyway, removing these strings should fix your problem:

```json
    "+qq",
    "+q",
    "+QQ",
    "+Q",


    "+VX",
    "+vx",
    "+v",
    "+V",
    "+WX",
    "+wx",
```

**Comment by far310** [comment]
ok problem solved, thank you very much for your efforts, Jesus bless you, seems "." Also not
