### ISSUE TITLE
TypeScript imports don't work as expected

### ISSUE THREAD

**Issue by mkadirtan** [alexzel/bad-words-next#9]
**Describe the bug**
TypeScript imports don't work.

**To Reproduce**
```typescript
import BadWordsNext from 'bad-words-next';

const badWordsNext = new BadWordsNext(); // Throws, not a class constructor exception!
```
---
```typescript
import * as BadWordsNext from 'bad-words-next';

// @ts-ignore
const badWordsNext = new BadWordsNext(); // Works correctly, but gives TypeScript errors.
```

**Environment (please complete the following information):**
 - Operating System: [e.g. macOS]
 - Node.js Version: [e.g. v16.17.0]

**Comment by alexzel** [comment]
I have tried to create a new TypeScript project and use the library. I don't get any errors.

```sh
$ node -v
v16.17.0

$ uname -a
Darwin mars.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:12:21 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T6000 arm64

$ mkdir badwordsTypescript
$ cd badwordsTypescript
$ npm init -y
$ npm install --save-dev typescript
$ vi tsconfig.json
```
Here is `tsconfig.json` content:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "target": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist"
  },
  "lib": ["es2015"]
}
```
Then I install the library and create the app script
```sh
$  npm install bad-words-next
$  mkdir src
$  vi src/app.ts
```
Here is `src/app.ts` content:
```ts
import BadWordsNext from 'bad-words-next';
import en from 'bad-words-next/data/en.json';
const badWordsNext = new BadWordsNext();
badWordsNext.add(en);
console.log(badWordsNext.filter('abc $h!tt'));
```
Then I run the app and get the expected result:
```sh
$  npx tsc && node dist/app.js 
  abc ***
```

**Comment by alexzel** [comment]
I have also tried to use it in browser with `create-react-app` and TypeScript template. Looks fine there as well.

```sh
npx create-react-app badwords-typescript --template typescript

cd badwords-typescript/
yarn add bad-words-next

yarn start
```

Then I edit `src/App.tsx` like this:
```ts
import React from 'react';
import './App.css';

import BadWordsNext from 'bad-words-next';
import en from 'bad-words-next/data/en.json';
const badWordsNext = new BadWordsNext();
badWordsNext.add(en);

function App() {
  return (
    <div className="App">
      <header className="App-header">
        {badWordsNext.filter('abc $h!tt')}
      </header>
    </div>
  );
}

export default App;
```

And get the expected result:
<img width="870" alt="Screen Shot 2023-04-06 at 5 03 10 AM" src="https://user-images.githubusercontent.com/1964324/230373675-c8cece51-04cf-431c-abc0-cbe86b6e9fcb.png">

**Comment by mkadirtan** [comment]
Yes, I tried the esModuleInterop flag and the default import worked, thanks 🙏 .

Couldn't it be better if we update the types to match the behavior? Because with the ts-ignore comment, the module works as expected but types don't.

**Comment by alexzel** [comment]
> Couldn't it be better if we update the types to match the behavior

I'm not sure how is that related to types, but I may be missing something. The library exports es and commonjs modules into `lib/index.mjs` and `lib/index.cjs` and it does not seem to be related to TypeScript or its types (the types go into `lib/index.d.ts` which does not care about modules system in use). The modules system in TypeScript can be configured through `module` field in `tsconfig.json`. It seems like the error happens when trying to use commonjs without `esModuleInterop` flag turned on (which I believe is a wrong configuration), so you might want to set `"module": "esnext"`.

**Comment by alexzel** [comment]
Closing due to `nothing to fix` reason. If you know what and how to fix here, please make a PR. Thanks!
